[package]
name = "databright_modelmarket"
version = "0.1.0"
authors = ["Florian Chlan <florian@chlan.net>"]

[dependencies]
web3 = { git = "https://github.com/tomusdrw/rust-web3", branch = "master" }
tokio-core = "0.1.16"
rust-ini = "0.11"
csv = "1"
log = "0.4.1"
env_logger = "0.5.10"